import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { ButtonStyled } from '../components/buttons.style'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Source on <a href="https://github.com/dephizee/wakaplug">Hafiz repo</a>
        </h1>
        <h2><code># this is an autogenerated page</code></h2>
        <p className={styles.description}>
          Get started by editing Logging in
          <Link href="login">
            <a>
              <code className={styles.code}><ButtonStyled>Login</ButtonStyled></code>
            </a>
          </Link>
        </p>

      </main>
    </div>
  )
}

export default Home
